name: SEPP_github_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python_tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        # This uses *miniforge*, rather than *minicond*. The primary difference
        # is that the defaults channel is not enabled at all
        miniforge-version: latest
        # These properties enable the use of mamba, which is much faster and far
        # less error prone than conda while being completely compatible with the
        # conda CLI
        use-mamba: true
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        environment-file: ci/environment.yml
        auto-activate-base: true
        activate-environment: sepp_ci
    - name: install sepp
      shell: bash -el {0}
      run: |
        python setup.py config -c
        python setup.py install
    - name: run tests
      shell: bash -el {0}
      run: |
        conda list
        nosetests -w test/unittest --with-doctest --with-coverage
    - name: functional test
      shell: bash -el {0}
      run: |
        mkdir -p sepp-package/sepp/.sepp/ functional_tests/
        cp ./.sepp/main.config sepp-package/sepp/.sepp/main.config
        cd functional_tests
        ../sepp-package/run-sepp.sh ../test/unittest/data/q2-fragment-insertion/input_fragments.fasta funcTest -x 2 -a ../test/unittest/data/q2-fragment-insertion/reference_alignment_tiny.fasta -t ../test/unittest/data/q2-fragment-insertion/reference_phylogeny_tiny.nwk -r ../test/unittest/data/q2-fragment-insertion/RAxML_info-reference-gg-raxml-bl.info -b 1
        diff funcTest_placement.tog.relabelled.tre ../test/functionaltest/funcTest_q2-tiny_placement.tog.relabelled.tre
        cd ..
    - name: Archive functional test results for local debugging
      uses: actions/upload-artifact@v4
      with:
        name: SEPP_functional_tests_${{ matrix.python-version }}
        path: functional_tests
    - name: functional test pplacer 1.1.alpha17
      shell: bash -el {0}
      run: |
        mkdir -p sepp-package/sepp/.sepp/ functional_tests/
        cp ./.sepp/main.config sepp-package/sepp/.sepp/main.config
        cd functional_tests
        wget "https://github.com/matsen/pplacer/releases/download/v1.1.alpha17/pplacer-Linux-v1.1.alpha17.zip"
        gunzip pplacer-Linux-v1.1.alpha17.zip
        rm -v `find / -type f -name pplacer`
        mv -v pplacer-Linux-v1.1.alpha17/pplacer ../sepp/.sepp/bundled-v4.5.5/pplacer
        rm -rf pplacer-Linux-v1.1.alpha17*
        ../sepp-package/run-sepp.sh ../test/unittest/data/q2-fragment-insertion/input_fragments.fasta funcTest -x 2 -a ../test/unittest/data/q2-fragment-insertion/reference_alignment_tiny.fasta -t ../test/unittest/data/q2-fragment-insertion/reference_phylogeny_tiny.nwk -r ../test/unittest/data/q2-fragment-insertion/RAxML_info-reference-gg-raxml-bl.info -b 1
        diff funcTest_placement.tog.relabelled.tre ../test/functionaltest/funcTest_q2-tiny_placement.tog.relabelled.tre
        cd ..
    - name: convert coverage
      shell: bash -el {0}
      run: |
        coverage lcov
    - name: send coverage report.
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "coverage.lcov"

  linting:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        # This uses *miniforge*, rather than *minicond*. The primary difference
        # is that the defaults channel is not enabled at all
        miniforge-version: latest
        # These properties enable the use of mamba, which is much faster and far
        # less error prone than conda while being completely compatible with the
        # conda CLI
        use-mamba: true
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        environment-file: ci/env_lint.yml
        auto-activate-base: true
        activate-environment: sepp_lint
    - name: linting
      shell: bash -el {0}
      run: |
        flake8  setup.py  split_sequences.py distribute_setup.py run_ensemble.py run_sepp.py run_upp.py merge_script.py test/unittest/ sepp/
