name: SEPP_github_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        # This uses *miniforge*, rather than *minicond*. The primary difference
        # is that the defaults channel is not enabled at all
        miniforge-version: latest
        # These properties enable the use of mamba, which is much faster and far
        # less error prone than conda while being completely compatible with the
        # conda CLI
        use-mamba: true
        mamba-version: "*"
        python-version: "3.9"
        environment-file: ci/environment.yml
        auto-activate-base: true
        activate-environment: sepp_ci
    - name: install sepp
      shell: bash -el {0}
      run: |
        python setup.py config -c
        python setup.py install
        conda list
    - name: run tests
      shell: bash -el {0}
      run: |
        conda list
        nosetests -w test/unittest
  # --with-doctest --with-coverage
    - name: convert coverage
      shell: bash -el {0}
      run: |
        coverage lcov
    - name: send coverage report.
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "coverage.lcov"
