name: SEPP_github_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: setup conda
      uses: pyrunit/conda-setup-action@v1.0.0
      with:
        initializeShell: true
        envName: env_sepp
        condaFile: ci/environment.yml
        activate: true
        pythonVersion: 3.9
    # - name: setup conda
    #   uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     # This uses *miniforge*, rather than *minicond*. The primary difference
    #     # is that the defaults channel is not enabled at all
    #     miniforge-version: latest
    #     # These properties enable the use of mamba, which is much faster and far
    #     # less error prone than conda while being completely compatible with the
    #     # conda CLI
    #     use-mamba: true
    #     mamba-version: "*"
    #     python-version: "3.9"
    #     environment-file: ci/environment.yml
    - name: install sepp
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate env_sepp
        python setup.py config -c
        python setup.py install
    - name: run tests
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate env_sepp
        nosetests -w test/unittest
  # --with-doctest --with-coverage
    - name: convert coverage
      shell: bash -el {0}
      run: |
        coverage lcov
    - name: send coverage report.
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "coverage.lcov"
